### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'

### ISSUE THREAD

**Issue by JinEui-Kim** [tkgix/Gix-Detailer#1]
```
Error calling: /data/project/stable-diffusion-webui/extensions/Gix-Detailer/scripts/gix_detailer.py/ui
Traceback (most recent call last):
  File "/data/project/stable-diffusion-webui/modules/scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "/data/project/stable-diffusion-webui/extensions/Gix-Detailer/scripts/gix_detailer.py", line 1482, in ui
    interrogator_names = refresh_interrogators()
  File "/data/project/stable-diffusion-webui/extensions/Gix-Detailer/scripts/gix_detailer.py", line 644, in refresh_interrogators
    for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'
```

error occured at restart webui after install extension.
there is any requirements?

**Comment by tkgix** [comment]
Thanks. I fixed it.

**Comment by tkgix** [comment]
> Thanks. I fixed it.
> 
> Please update and see again

Thanks. I fixed it.

Please update and see again

**Comment by JinEui-Kim** [comment]
Thanks.
It works well
